version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: nextcall-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./nextcall_api
    container_name: nextcall-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/nextcalldb
      - JWT_SECRET=I_am_JWT_SECRET
    depends_on:
      - mongo

  ui:
    build: ./nextcall_ui
    container_name: nextcall-ui
    restart: always
    ports:
      - "4300:80"
    depends_on:
      - api

volumes:
  mongo-data:
